### ISSUE TITLE
option to prepend a file with a given block

### ISSUE THREAD

**Issue by huafu** [ghempton/ember-script#42]
This case appeared to me when I wanted to use `import` from ES6 syntax but is also the case for anybody who want to use Ember another way and do a `Ember = require 'ember'` for example.

The problem is that EmberScript would prepend the whole script with `var $get = Ember.get, $set = Ember.set;` and that before the first line of the `.em` file where there might be `Ember = require 'ember'`.

So maybe there can be an option to tell EmberScript to prepend the whole thing with some block like that:

``` coffee
$$$
# this can be anywhere in the file, all such sections would be concatenated and
# prepended before the var $get = Ember.get...
Ember = require 'ember'
$$$
```

or cleaner but more specific to this case, having a way to tell EmberScript where to take `Ember` from with some comment header in the file:

``` coffee
# $Ember$ = require 'ember'
# or, in the case of ES6:
# `import $Ember$ from 'ember'`

class MyView extend Ember.View
  tagName: #...
```

I'm pretty sure my syntax isn't the best, I'm just trying to show some possible solutions so that at the end instead of having:

``` js
// Generated by EmberScript 0.0.14
var Ember, PostsController;
var get$ = Ember.get;
var set$ = Ember.set;
Ember = require('ember');
PostsController = Ember.ArrayController.extend();
```

we'd have:

``` js
// Generated by EmberScript 0.0.14
var Ember = require('ember');
var PostsController;
var get$ = Ember.get;
var set$ = Ember.set;
PostsController = Ember.ArrayController.extend();
```

for a source being:

``` coffee
Ember = require 'ember'
class PostsController extends Ember.ArrayController
```

**Comment by jfelchner** [comment]
@huafu can we go ahead and close this out please?

**Comment by huafu** [comment]
@jfelchner the issue is from 4 years ago and I am no more using ember in my projects, but looking at my issue and the section of the readme @kristianmandrup referred too, I guess that would do the trick, so yeah this can be closed I think...
