### ISSUE TITLE
emberscript.com does not work anymore

### ISSUE THREAD

**Issue by dynamix** [ghempton/ember-script#51]
"Site temporarily disabled - This page has been temporarily disabled due to a misconfigured custom domain."

Thats all I see.

**Comment by perlun** [comment]
Still the same problem.

**Comment by seanlinsley** [comment]
Just to record it: http://emberscript.com/

![screen shot 2015-02-13 at 2 32 56 pm](https://cloud.githubusercontent.com/assets/688886/6194803/3c3eaa40-b38d-11e4-9817-fcaf421661db.png)

**Comment by zekefast** [comment]
Site does not respond at all now.

**Comment by ghempton** [comment]
Fixed

**Comment by zekefast** [comment]
Thank you!
